name: Build Meteoric Stable 13.1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: 13.1-new

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex git libssl-dev libelf-dev clang lld llvm libncurses-dev gcc-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # 1. Створюємо конфігурацію
          make O=out vendor/meteoric_defconfig
          
          # 2. ОЦЕЙ РЯДОК ОБОВ'ЯЗКОВО ПОТРІБЕН (Він лікує забаганий білд):
          make O=out ARCH=arm64 CC=clang olddefconfig
          
          # 3. Основна збірка ядра та модулів
          make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip

      - name: Upload Kernel and Modules
        uses: actions/upload-artifact@v4
        with:
          name: Meteoric-Kebab-Stable
          path: |
            out/arch/arm64/boot/Image*
            out/drivers/beast_mode/backdr84.ko
